### ISSUE TITLE
AttributeError: 'module' object has no attribute 'AF_UNIX'

### ISSUE THREAD

**Issue by ashishkaransingh** [atroncy/kapacitor_prophet-udf#1]
Hi,

Thanks for the script!

Currently getting the following error in kapacitor Log file when I start kapacitor from command line: 
kapacitord.exe -config kapacitor.conf
ts=2019-11-25T07:59:18.297-05:00 lvl=info msg="UDF log" service=udf text=" server = Server(path, accepter())"
ts=2019-11-25T07:59:18.297-05:00 lvl=info msg="UDF log" service=udf text=" File \"C:\\Monitoring\\kapacitor_udf\\kapacitor\\udf\\agent\\py\\kapacitor\\udf\\agent.py\", line 180, in __init__"
ts=2019-11-25T07:59:18.298-05:00 lvl=info msg="UDF log" service=udf text=" self._listener = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM )"
ts=2019-11-25T07:59:18.298-05:00 lvl=info msg="UDF log" service=udf text="AttributeError: 'module' object has no attribute 'AF_UNIX'"
Do i need to use Socket or something similar to this "#socket = "/path/to/socket"" ? If yes then please advise.

Following is the UDF section form kapactor.conf

[udf.functions.prophet]
prog = "C:/ProgramData/Anaconda2/python.exe"
args = ["-u", "C:/Monitoring/kapacitor_udf/kapacitor/udf/agent/examples/prophet/prophet.py"]
timeout = "60s"
[udf.functions.prophet.env]
PYTHONPATH = "C:/Monitoring/kapacitor_udf/kapacitor/udf/agent/py"

I can use Prophet package outside kapacitor (Anaconda jupyter notebook), therefore I understand that I need to configure UDF in a very specific way to be able to use Prophet.py as UDF with Kapacitor.

I know there has been issues using UDF with python3 therefore i have been trying with python2 conda environment.
Kapacitor Version: 1.5.3
OS: Windows

Other references:
https://community.influxdata.com/t/prophet-forecasting-udf-unable-to-write-response-to-influxdb/6348/20

**Comment by atroncy** [comment]
Hi, by default the script attempt to maintain a connection to an unix domain socket on this file /tmp/udf_prophet.sock, unless you specify another path as the first args. You need to make sure, that both kapacitor & this script have the correct right to read/write on this file. 

I don't know if Windows support unix domain socket.
And I have been unable to run this script on python3 the last time I tried, it worked with python 2.7.

**Comment by ashishkaransingh** [comment]
Thanks a lot @atroncy, i switched to linux with python 2 and been able to make a lot of progress.
I think i am nearing the finish line :)
